/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import Casa.*;
import Dispositivo.*;
import Interfaces.ConsumoEnergia;
import Sensores.*;

/**
 *
 * @author magal
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    public static VentanaPrincipal instanciaGlobal;
    private Vivienda casita;
    public String reporteTemporal = "";
    
    public VentanaPrincipal(Vivienda casaCargada) {
        initComponents();// inicia el grafico
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.WRAP_TAB_LAYOUT);
    
        // CONGELAMOS EL JFRAME 
        this.setSize(600, 480); 
        this.setResizable(false); // Evita que se deforme
        this.setLocationRelativeTo(null); // Centra la ventana en tu monitor

        // 3. CONGELAMOS EL TAMAÑO DE LAS PESTAÑAS
        java.awt.Dimension tamanoTabs = new java.awt.Dimension(560,300);
        jTabbedPane1.setPreferredSize(tamanoTabs);
        jTabbedPane1.setSize(tamanoTabs);

        this.casita=casaCargada;
        VentanaPrincipal.instanciaGlobal = this;
        
        if (this.casita != null && this.casita.getHistorialAcumulado() != null) {
            txtAreaHistorial.setText(this.casita.getHistorialAcumulado());
        }
        this.reporteTemporal = "";
        
        for (Habitacion h : casita.getHabitaciones()) {
        comboHabDispositivos.addItem(h.getNombre());
        comboHabSensores.addItem(h.getNombre());
        comboHabEventos.addItem(h.getNombre());
        comboOpcionesConsumo.addItem(h.getNombre());
    }
    }
    public void registrarEnHistorial(String mensaje) {
 
        java.time.LocalTime hora = java.time.LocalTime.now();
        String horaFormateada = String.format("%02d:%02d:%02d", hora.getHour(), hora.getMinute(), hora.getSecond());
        String lineaCompleta = "[" + horaFormateada + "] - " + mensaje + "\n";

        txtAreaHistorial.append(lineaCompleta);
    
        this.reporteTemporal += lineaCompleta; //copia temporal para el jOptionPane de simulacion
        if (casita != null) {
        String historialViejo = casita.getHistorialAcumulado();
        casita.setHistorialAcumulado(historialViejo + lineaCompleta);
    }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarSalir = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ESTADO = new javax.swing.JPanel();
        btnVerEstado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEstado = new javax.swing.JTextArea();
        btnControlarDispositivo = new javax.swing.JButton();
        btnEliminarCasa = new javax.swing.JButton();
        CREARHAB = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomHabitacion = new javax.swing.JTextField();
        btnCrearHabitacion = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        AGSENSOR = new javax.swing.JPanel();
        comboHabSensores = new javax.swing.JComboBox<>();
        comboTipoSensor = new javax.swing.JComboBox<>();
        txtNomSensor = new javax.swing.JTextField();
        txtIdSensor = new javax.swing.JTextField();
        btnAgregarSensor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        HISTORIAL = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaHistorial = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CONSUMO = new javax.swing.JPanel();
        txtAreaConsum = new javax.swing.JScrollPane();
        txtAreaConsumo = new javax.swing.JTextArea();
        btnCalcularConsumo = new javax.swing.JButton();
        comboOpcionesConsumo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        AGDISPOSITIVOS = new javax.swing.JPanel();
        comboHabDispositivos = new javax.swing.JComboBox<>();
        comboTipoDispositivo = new javax.swing.JComboBox<>();
        txtIdDispositivo = new javax.swing.JTextField();
        txtNomDispositivo = new javax.swing.JTextField();
        btnAgregarDispositivo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        SIMULACION = new javax.swing.JPanel();
        comboHabEventos = new javax.swing.JComboBox<>();
        comboTipoEvento = new javax.swing.JComboBox<>();
        btnSimularEvento = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarSalir.setBackground(new java.awt.Color(0, 204, 0));
        btnGuardarSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardarSalir.setText("GUARDAR CAMBIOS");
        btnGuardarSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardarSalir.addActionListener(this::btnGuardarSalirActionPerformed);
        getContentPane().add(btnGuardarSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 405, 600, 40));

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 102, 102));
        jTabbedPane1.setToolTipText("Ver Estado");
        jTabbedPane1.setName(""); // NOI18N

        ESTADO.setMaximumSize(new java.awt.Dimension(800, 800));
        ESTADO.setMinimumSize(new java.awt.Dimension(800, 800));
        ESTADO.setPreferredSize(new java.awt.Dimension(800, 800));
        ESTADO.setRequestFocusEnabled(false);

        btnVerEstado.setBackground(new java.awt.Color(0, 255, 0));
        btnVerEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVerEstado.setText("Actualizar Estado");
        btnVerEstado.addActionListener(this::btnVerEstadoActionPerformed);

        txtAreaEstado.setBackground(new java.awt.Color(153, 153, 153));
        txtAreaEstado.setColumns(20);
        txtAreaEstado.setRows(5);
        jScrollPane1.setViewportView(txtAreaEstado);

        btnControlarDispositivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnControlarDispositivo.setText("Cambiar Estado de Dispositivos");
        btnControlarDispositivo.addActionListener(this::btnControlarDispositivoActionPerformed);

        btnEliminarCasa.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarCasa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarCasa.setText("Eliminar Casa");
        btnEliminarCasa.addActionListener(this::btnEliminarCasaActionPerformed);

        javax.swing.GroupLayout ESTADOLayout = new javax.swing.GroupLayout(ESTADO);
        ESTADO.setLayout(ESTADOLayout);
        ESTADOLayout.setHorizontalGroup(
            ESTADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESTADOLayout.createSequentialGroup()
                .addGroup(ESTADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ESTADOLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnVerEstado)
                        .addGap(84, 84, 84)
                        .addComponent(btnEliminarCasa))
                    .addGroup(ESTADOLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ESTADOLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(btnControlarDispositivo)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        ESTADOLayout.setVerticalGroup(
            ESTADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ESTADOLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnControlarDispositivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ESTADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarCasa)
                    .addComponent(btnVerEstado))
                .addContainerGap())
        );

        jTabbedPane1.addTab("VER ESTADO", ESTADO);

        jLabel1.setText("Nombre:");

        btnCrearHabitacion.setBackground(new java.awt.Color(0, 255, 0));
        btnCrearHabitacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCrearHabitacion.setText("Guardar Habitacion ");
        btnCrearHabitacion.addActionListener(this::btnCrearHabitacionActionPerformed);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/pieza.png"))); // NOI18N

        javax.swing.GroupLayout CREARHABLayout = new javax.swing.GroupLayout(CREARHAB);
        CREARHAB.setLayout(CREARHABLayout);
        CREARHABLayout.setHorizontalGroup(
            CREARHABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREARHABLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnCrearHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CREARHABLayout.createSequentialGroup()
                .addGap(0, 165, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNomHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(117, 117, 117))
        );
        CREARHABLayout.setVerticalGroup(
            CREARHABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CREARHABLayout.createSequentialGroup()
                .addGroup(CREARHABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CREARHABLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CREARHABLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(CREARHABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(16, 16, 16)
                .addComponent(btnCrearHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CREAR HABITACION", CREARHAB);

        comboHabSensores.addActionListener(this::comboHabSensoresActionPerformed);

        comboTipoSensor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sensor de Movimiento", "Sensor de Temperatura", "Sensor de Humo" }));

        txtNomSensor.addActionListener(this::txtNomSensorActionPerformed);

        btnAgregarSensor.setBackground(new java.awt.Color(0, 255, 0));
        btnAgregarSensor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarSensor.setText("Guardar Sensor");
        btnAgregarSensor.addActionListener(this::btnAgregarSensorActionPerformed);

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("ID:");

        jLabel12.setText("HABITACION:");

        jLabel13.setText("TIPO:");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/sensor.jpg"))); // NOI18N

        javax.swing.GroupLayout AGSENSORLayout = new javax.swing.GroupLayout(AGSENSOR);
        AGSENSOR.setLayout(AGSENSORLayout);
        AGSENSORLayout.setHorizontalGroup(
            AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGSENSORLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboHabSensores, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel3))
                .addGap(72, 72, 72)
                .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AGSENSORLayout.createSequentialGroup()
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIdSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(AGSENSORLayout.createSequentialGroup()
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboTipoSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jLabel17)))
                .addGap(53, 53, 53))
            .addGroup(AGSENSORLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnAgregarSensor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AGSENSORLayout.setVerticalGroup(
            AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGSENSORLayout.createSequentialGroup()
                .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AGSENSORLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboHabSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(AGSENSORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnAgregarSensor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AGSENSORLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel17)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("AGREGAR SENSOR", AGSENSOR);

        txtAreaHistorial.setEditable(false);
        txtAreaHistorial.setBackground(new java.awt.Color(153, 153, 153));
        txtAreaHistorial.setColumns(20);
        txtAreaHistorial.setRows(5);
        jScrollPane2.setViewportView(txtAreaHistorial);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/historial.jpg"))); // NOI18N
        jLabel19.setText("jLabel19");

        jButton1.setText("Borrar Historial");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout HISTORIALLayout = new javax.swing.GroupLayout(HISTORIAL);
        HISTORIAL.setLayout(HISTORIALLayout);
        HISTORIALLayout.setHorizontalGroup(
            HISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HISTORIALLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(HISTORIALLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HISTORIALLayout.setVerticalGroup(
            HISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HISTORIALLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HISTORIALLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jButton1))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HISTORIAL", HISTORIAL);

        CONSUMO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAreaConsumo.setBackground(new java.awt.Color(153, 153, 153));
        txtAreaConsumo.setColumns(20);
        txtAreaConsumo.setRows(5);
        txtAreaConsum.setViewportView(txtAreaConsumo);

        CONSUMO.add(txtAreaConsum, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 380, 190));

        btnCalcularConsumo.setBackground(new java.awt.Color(0, 255, 0));
        btnCalcularConsumo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalcularConsumo.setText("CALCULAR");
        btnCalcularConsumo.addActionListener(this::btnCalcularConsumoActionPerformed);
        CONSUMO.add(btnCalcularConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 60, -1, -1));

        comboOpcionesConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toda la Casa " }));
        CONSUMO.add(comboOpcionesConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Calcular Consumo en:");
        CONSUMO.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 23, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/e6a0372660ea7aef2d333385772758e7.jpg"))); // NOI18N
        CONSUMO.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jTabbedPane1.addTab("CONSUMO ENERGETICO", CONSUMO);

        comboHabDispositivos.addActionListener(this::comboHabDispositivosActionPerformed);

        comboTipoDispositivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luz", "Aire Acondicionado", "Ventana", "Alarma" }));

        txtIdDispositivo.addActionListener(this::txtIdDispositivoActionPerformed);

        txtNomDispositivo.addActionListener(this::txtNomDispositivoActionPerformed);

        btnAgregarDispositivo.setBackground(new java.awt.Color(0, 255, 0));
        btnAgregarDispositivo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarDispositivo.setText("Guardar Dispositivo");
        btnAgregarDispositivo.addActionListener(this::btnAgregarDispositivoActionPerformed);

        jLabel5.setText("NOMBRE:");

        jLabel6.setText("ID:");

        jLabel10.setText("HABITACION:");

        jLabel11.setText("TIPO:");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/aire.jpg"))); // NOI18N

        javax.swing.GroupLayout AGDISPOSITIVOSLayout = new javax.swing.GroupLayout(AGDISPOSITIVOS);
        AGDISPOSITIVOS.setLayout(AGDISPOSITIVOSLayout);
        AGDISPOSITIVOSLayout.setHorizontalGroup(
            AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGDISPOSITIVOSLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AGDISPOSITIVOSLayout.createSequentialGroup()
                        .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(comboHabDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97)
                        .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboTipoDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AGDISPOSITIVOSLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(btnAgregarDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        AGDISPOSITIVOSLayout.setVerticalGroup(
            AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AGDISPOSITIVOSLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboHabDispositivos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTipoDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AGDISPOSITIVOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnAgregarDispositivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("AGREGAR DISPOSITIVO", AGDISPOSITIVOS);

        comboTipoEvento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Movimiento", "Temperatura", "Humo" }));

        btnSimularEvento.setBackground(new java.awt.Color(0, 255, 0));
        btnSimularEvento.setText("Ejecutar Simulacion");
        btnSimularEvento.addActionListener(this::btnSimularEventoActionPerformed);

        jLabel7.setText("Habitacion:");

        jLabel8.setText("Tipo de Evento:");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/simula.jpg"))); // NOI18N

        javax.swing.GroupLayout SIMULACIONLayout = new javax.swing.GroupLayout(SIMULACION);
        SIMULACION.setLayout(SIMULACIONLayout);
        SIMULACIONLayout.setHorizontalGroup(
            SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIMULACIONLayout.createSequentialGroup()
                .addGroup(SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SIMULACIONLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel7)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SIMULACIONLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)))
                .addGroup(SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboTipoEvento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboHabEventos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(jLabel18))
            .addGroup(SIMULACIONLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btnSimularEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SIMULACIONLayout.setVerticalGroup(
            SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SIMULACIONLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SIMULACIONLayout.createSequentialGroup()
                        .addGroup(SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboHabEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(28, 28, 28)
                        .addGroup(SIMULACIONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(SIMULACIONLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)))
                .addGap(20, 20, 20)
                .addComponent(btnSimularEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("SIMULAR EVENTO", SIMULACION);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 370));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logos/43a3dc3b3a2ed8425f6ce3e26acde904.jpg"))); // NOI18N
        jLabel2.setText("PANEL DE CONTROL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearHabitacionActionPerformed
        String nombreH = txtNomHabitacion.getText().trim();

        if (nombreH.isEmpty()) { //si esta vacio
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Por favor, ingrese un nombre para la habitación.", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        casita.agregarHabitacion(new Habitacion(nombreH));

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Habitacion:" + nombreH + "creada con exito!");

        txtNomHabitacion.setText("");
        comboHabDispositivos.addItem(nombreH);
        comboHabSensores.addItem(nombreH);
        comboHabEventos.addItem(nombreH);
        comboOpcionesConsumo.addItem(nombreH);
        
        registrarEnHistorial("Se construyó una nueva habitación: " + nombreH);
        
    }//GEN-LAST:event_btnCrearHabitacionActionPerformed

    private void btnAgregarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarSensorActionPerformed
        if (casita.getHabitaciones().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes crear una habitacion primero.");
            return;
        }

        int indiceHab = comboHabSensores.getSelectedIndex();
        Habitacion habDestino = casita.getHabitaciones().get(indiceHab);

        String tipo = comboTipoSensor.getSelectedItem().toString();
        String nombreS = txtNomSensor.getText().trim();
        String idS = txtIdSensor.getText().trim();

        if (nombreS.isEmpty() || idS.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Completa el nombre y el ID del sensor.");
            return;
        }

        switch (tipo) {
            case "Sensor de Movimiento": 
                habDestino.agregarSensor(new SensorMovimiento(nombreS, idS)); 
                break;
            case "Sensor de Temperatura": 
                habDestino.agregarSensor(new SensorTemperatura(nombreS, idS)); 
                break;
            case "Sensor de Humo": 
                habDestino.agregarSensor(new SensorHumo(nombreS, idS)); 
                break;
        }

        txtNomSensor.setText("");
        txtIdSensor.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "¡" + tipo + " agregado con éxito a " + habDestino.getNombre() + "!");
        registrarEnHistorial("Sensor instalado: " + nombreS + " en la habitación " + habDestino.getNombre());
    }//GEN-LAST:event_btnAgregarSensorActionPerformed

    private void txtNomSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomSensorActionPerformed

    private void btnSimularEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularEventoActionPerformed
        if (comboHabEventos.getSelectedItem() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay habitaciones para simular eventos.");
            return;
        }
        VentanaPrincipal.instanciaGlobal.reporteTemporal = "";

        int idx = comboHabEventos.getSelectedIndex();
        Habitacion hab = casita.getHabitaciones().get(idx);
        String tipoEv = comboTipoEvento.getSelectedItem().toString();

        try {
            if (tipoEv.equals("Movimiento")) {
                    boolean tieneSensor = false; //vemos si tiene senspr de movimiento
                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorMovimiento) tieneSensor = true;
                    }
                    if (!tieneSensor) {
                        javax.swing.JOptionPane.showMessageDialog(this, "No hay Sensores de Movimiento en " + hab.getNombre(), "Sin Sensor", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    String horaStr = javax.swing.JOptionPane.showInputDialog(this, "¿Que hora es? (0-23):");
                    if (horaStr == null) return; 

                    int hora = Integer.parseInt(horaStr.trim());
                    for (Habitacion h : casita.getHabitaciones()) {
                        h.setHora(hora);
                    }

                    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Hay personas moviendose ahora en " + hab.getNombre() + "?", "Movimiento", javax.swing.JOptionPane.YES_NO_OPTION);
                    boolean hayMov = (respuesta == javax.swing.JOptionPane.YES_OPTION);

                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorMovimiento) s.setEstadoAlerta(hayMov);
                    }
                } 
                else if (tipoEv.equals("Temperatura")) {
                    boolean tieneSensor = false;
                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorTemperatura) tieneSensor = true;
                    }
                    if (!tieneSensor) {
                        javax.swing.JOptionPane.showMessageDialog(this, "No hay Sensores de Temperatura en " + hab.getNombre(), "Sin Sensor", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    String tempStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la temperatura actual (°C):");
                    if (tempStr == null) return; 

                    double temp = Double.parseDouble(tempStr.trim());
                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorTemperatura) {
                            ((SensorTemperatura) s).setTempAmbiente(temp);
                        }
                    }
                } 
                else if (tipoEv.equals("Humo")) {
                    boolean tieneSensor = false;
                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorHumo) tieneSensor = true;
                    }
                    if (!tieneSensor) {
                        javax.swing.JOptionPane.showMessageDialog(this, "No hay Sensores de Humo en " + hab.getNombre(), "Sin Sensor", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    int respuesta = javax.swing.JOptionPane.showConfirmDialog(this, "¿Se detecta humo en " + hab.getNombre() + "?", "Humo", javax.swing.JOptionPane.YES_NO_OPTION);
                    boolean hayHumo = (respuesta == javax.swing.JOptionPane.YES_OPTION);

                    for (Sensor s : hab.getSensores()) {
                        if (s instanceof SensorHumo) s.setEstadoAlerta(hayHumo);
                    }
                    
                }
                for (Sensor s : hab.getSensores()) {
                if (tipoEv.equals("Movimiento") && s instanceof SensorMovimiento) {
                    s.evaluar(hab);
                }
                else if (tipoEv.equals("Temperatura") && s instanceof SensorTemperatura) {
                    s.evaluar(hab);
                }
                else if (tipoEv.equals("Humo") && s instanceof SensorHumo) {
                    s.evaluar(hab);
                }
        }
                
                
                if (VentanaPrincipal.instanciaGlobal.reporteTemporal.isEmpty()) {//si esta vacio no paso nada
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Todo tranquilo en " + hab.getNombre() + ".\nNo se requirio ninguna accion automatica.", 
                        "Sin Novedades", 
                        javax.swing.JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "Se ejecutaron las siguientes acciones:\n\n" + VentanaPrincipal.instanciaGlobal.reporteTemporal, 
                        "Reporte Detallado", 
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                }


            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error: Ingresa numeros validos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        
        
    }//GEN-LAST:event_btnSimularEventoActionPerformed

    private void btnCalcularConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularConsumoActionPerformed
        txtAreaConsumo.setText(""); // Limpiamos la pantalla

        if (casita.getHabitaciones().isEmpty()) {
            txtAreaConsumo.append("No hay habitaciones registradas.\n");
            return;
        }
        int opcion = comboOpcionesConsumo.getSelectedIndex();

        if (opcion == 0) {
            double consumoTotalCasa = 0.0;
            txtAreaConsumo.append("--- REPORTE GENERAL DE LA VIVIENDA ---\n\n");

            for (Habitacion h : casita.getHabitaciones()) {
                double consumoHab = 0.0;
                txtAreaConsumo.append(h.getNombre() + ":\n");

                for (Dispositivo d : h.getDispositivos()) {
                    if (d instanceof ConsumoEnergia) {
                        double gasto = ((ConsumoEnergia) d).obtenerConsumoActual();
                        consumoHab += gasto;
                        txtAreaConsumo.append( d.getNombre() + ": " + gasto + " kWh\n");
                    }
                }
                txtAreaConsumo.append("Consumo de:" + h.getNombre() + ": " + consumoHab + " kWh\n\n");
                consumoTotalCasa += consumoHab;
            }

            txtAreaConsumo.append("=========================================\n");
            txtAreaConsumo.append("CONSUMO TOTAL: " + consumoTotalCasa + " kWh\n");
            txtAreaConsumo.append("=========================================\n");
} 

        else {
            Habitacion h = casita.getHabitaciones().get(opcion - 1);
            double consumoHab = 0.0;

            txtAreaConsumo.append("--- REPORTE DE: " + h.getNombre().toUpperCase() + " ---\n\n");

            for (Dispositivo d : h.getDispositivos()) {
                if (d instanceof ConsumoEnergia) {
                    double gasto = ((ConsumoEnergia) d).obtenerConsumoActual();
                    consumoHab += gasto;
                    txtAreaConsumo.append( d.getNombre() + ": " + gasto + " kWh\n");
                }
            }

            txtAreaConsumo.append("\n=========================================\n");
            txtAreaConsumo.append("CONSUMO TOTAL DE LA HABITACION: " + consumoHab + " kWh\n");
            txtAreaConsumo.append("=========================================\n");
}
    }//GEN-LAST:event_btnCalcularConsumoActionPerformed

    private void btnGuardarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSalirActionPerformed
        Archivo.guardarCasa(casita);

        javax.swing.JOptionPane.showMessageDialog(this, "¡Datos guardados correctamente! Cerrando sistema...");

        System.exit(0);//cerrar programa de forma segura
    }//GEN-LAST:event_btnGuardarSalirActionPerformed

    private void comboHabSensoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHabSensoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHabSensoresActionPerformed

    private void btnEliminarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCasaActionPerformed
        int confirmar = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "¿Estas seguro de que deseas eliminar la casa?\nSe borrarán todas las habitaciones, dispositivos y sensores de la memoria.",
            "¡ADVERTENCIA!",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            java.time.LocalDateTime ahora = java.time.LocalDateTime.now();
            java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
            String fechaHora = ahora.format(formato);
            txtAreaHistorial.append("[" + fechaHora + "] SISTEMA:SE ELIMINO LA CASA.\n");
            casita = new Vivienda();
            txtAreaEstado.setText("No hay ninguna casa creada o los datos fueron eliminados.");

            comboHabDispositivos.removeAllItems();
            comboHabSensores.removeAllItems();
            comboHabEventos.removeAllItems();

            comboOpcionesConsumo.removeAllItems();
            comboOpcionesConsumo.addItem("Toda la Casa");

            txtAreaEstado.setText("");
            txtAreaConsumo.setText("");

            javax.swing.JOptionPane.showMessageDialog(this, "La casa ha sido eliminada. El sistema se ha reiniciado por completo.");
        }
    }//GEN-LAST:event_btnEliminarCasaActionPerformed

    private void btnVerEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadoActionPerformed
        txtAreaEstado.setText("");

        if (casita.getHabitaciones().isEmpty()) {
            txtAreaEstado.append("La casa esta vacia, crea una habitacion!\n");
            return; }
        txtAreaEstado.append("=== ESTADO ACTUAL DE LA VIVIENDA ===\n\n");

        for (Habitacion h : casita.getHabitaciones()) {
            txtAreaEstado.append("Habitación: " + h.getNombre().toUpperCase() + "\n");
            txtAreaEstado.append("[Dispositivos]\n");
            if (h.getDispositivos().isEmpty()) txtAreaEstado.append("No hay dispositivos registrados\n");
            for (Dispositivo d : h.getDispositivos()) {
                String estadoVisual = "";
                // Si es ventana usamos Abierta/Cerrada, sino Encendido/Apagado
                if (d instanceof Ventana) {
                    estadoVisual = d.estaEncendido() ? "ABIERTA" : "CERRADA";
                } else {
                    estadoVisual = d.estaEncendido() ? "ENCENDIDO" : "APAGADO";
                }
                String tipoDispositivo = d.getClass().getSimpleName();
                txtAreaEstado.append(tipoDispositivo+ ": " + d.getNombre() + " [ID: " + d.getId()+ " ] -> [" + estadoVisual + "]\n");
            }

            txtAreaEstado.append("[Sensores]\n");
            if (h.getSensores().isEmpty()) txtAreaEstado.append("No hay sensores registrados\n");
            for (Sensor s : h.getSensores()) {
                String estado= s.isEstadoAlerta()? "Si" : "No";
                String tipoSensor = s.getClass().getSimpleName();

                txtAreaEstado.append(tipoSensor+ ": " + s.getNombre() + " [ID: " + s.getId() + "] -> Alerta: " + estado +"\n");
            }
            txtAreaEstado.append("------------------------------------------\n");
        }
    }//GEN-LAST:event_btnVerEstadoActionPerformed

    private void btnControlarDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnControlarDispositivoActionPerformed
        if (casita.getHabitaciones().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No hay habitaciones creadas.");
            return;
        }
        //lista de habitaciones
        String[] nombresHabitaciones = new String[casita.getHabitaciones().size()];
        for (int i = 0; i < casita.getHabitaciones().size(); i++) {
            nombresHabitaciones[i] = casita.getHabitaciones().get(i).getNombre();
        }

        String habSeleccionada = (String) javax.swing.JOptionPane.showInputDialog(
            this, "Selecciona la habitación:", "Control de Dispositivos",
            javax.swing.JOptionPane.QUESTION_MESSAGE, null, nombresHabitaciones, nombresHabitaciones[0]
        );

        if (habSeleccionada == null) return;

        // Buscar la habitacion en la memoria
        Habitacion habActual = null;
        for (Habitacion h : casita.getHabitaciones()) {
            if (h.getNombre().equals(habSeleccionada)) {
                habActual = h;
                break;
            }
        }

        if (habActual.getDispositivos().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Esta habitación no tiene dispositivos configurados.");
            return;
        }

        //lista con los dispositivos de esa habitación
        String[] nombresDispositivos = new String[habActual.getDispositivos().size()];
        for (int i = 0; i < habActual.getDispositivos().size(); i++) {
            nombresDispositivos[i] = habActual.getDispositivos().get(i).getNombre();
        }

        // pedir que elija el dispositivo
        String dispSeleccionado = (String) javax.swing.JOptionPane.showInputDialog(
            this, "Selecciona el aparato que deseas controlar:", "Control de Dispositivos",
            javax.swing.JOptionPane.QUESTION_MESSAGE, null, nombresDispositivos, nombresDispositivos[0]
        );

        if (dispSeleccionado == null) return;

        Dispositivo dispActual = null;
        for (Dispositivo d : habActual.getDispositivos()) {
            if (d.getNombre().equals(dispSeleccionado)) {
                dispActual = d;
                break;
            }
        }
        boolean estadoActual = false;
        if (dispActual instanceof Luz) {
            estadoActual = ((Luz) dispActual).estaEncendido();
        } else if (dispActual instanceof AireAcondicionado) {
            estadoActual = ((AireAcondicionado) dispActual).estaEncendido();
        } else if (dispActual instanceof Ventana) {
            estadoActual = ((Ventana) dispActual).estaAbierta();
        }

        // se crea como un switch (JToggleButton)
        javax.swing.JToggleButton btnSwitch = new javax.swing.JToggleButton();
        btnSwitch.setSelected(estadoActual); // Lo hunde si esta prendido, lo levanta si esta apagado
        btnSwitch.setText(estadoActual ? "ENCENDIDO / ABIERTO" : "APAGADO / CERRADO");

        // Hacer que el texto cambie en vivo cuando el usuario lo toca
        btnSwitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if (btnSwitch.isSelected()) {
                    btnSwitch.setText("ENCENDIDO / ABIERTO");
                } else {
                    btnSwitch.setText("APAGADO / CERRADO");
                }
            }
        });

        // meter el Switch adentro de una ventanita
        Object[] contenidoVentana = {
            "Toca el botón para cambiar el estado de: " + dispActual.getNombre(),
            btnSwitch
        };

        int opcion = javax.swing.JOptionPane.showConfirmDialog(
            this,
            contenidoVentana,
            "Controlador Manual",
            javax.swing.JOptionPane.OK_CANCEL_OPTION,
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (opcion == javax.swing.JOptionPane.OK_OPTION) {
            boolean nuevoEstado = btnSwitch.isSelected(); // se ve como dejo el boton el usuario

            if (nuevoEstado == true) {
                dispActual.encender();
            } else {
                dispActual.apagar();
            }btnVerEstado.doClick();

            // Refresca el texto de Ver Estado
            btnVerEstadoActionPerformed(null);

            String estadoTexto = nuevoEstado ? "ENCENDIDO" : "APAGADO";
            registrarEnHistorial("Usuario cambió el estado manual de " + dispActual.getNombre() + " a " + estadoTexto);
        }
    }//GEN-LAST:event_btnControlarDispositivoActionPerformed

    private void btnAgregarDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDispositivoActionPerformed
        if (casita.getHabitaciones().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debes crear una habitacion primero.");
            return;
        }

        int indiceHab = comboHabDispositivos.getSelectedIndex(); // numero de opcion
        Habitacion habDestino = casita.getHabitaciones().get(indiceHab); // buscamos esa hab en la memoria

        String tipo = comboTipoDispositivo.getSelectedItem().toString();
        String nombreD = txtNomDispositivo.getText().trim();
        String idD = txtIdDispositivo.getText().trim();

        // validamos que no haya dejado textos en blanco
        if (nombreD.isEmpty() || idD.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Completa el nombre y el ID del dispositivo.");
            return;
        }

        switch (tipo) {
            case "Luz":
            habDestino.agregarDispositivo(new Luz(nombreD, idD));
            break;
            case "Aire Acondicionado":
            habDestino.agregarDispositivo(new AireAcondicionado(nombreD, idD));
            break;
            case "Ventana":
            habDestino.agregarDispositivo(new Ventana(nombreD, idD));
            break;
            case "Alarma":
            habDestino.agregarDispositivo(new Alarma(nombreD, idD));
            break;
        }

        // 5. Limpiamos las casillas y mostramos éxito
        txtNomDispositivo.setText("");
        txtIdDispositivo.setText("");
        javax.swing.JOptionPane.showMessageDialog(this, "¡" + tipo + " agregado con éxito a " + habDestino.getNombre() + "!");
        registrarEnHistorial("Dispositivo creado: " + nombreD + " (" + tipo + ") en la habitación " + habDestino.getNombre());
    }//GEN-LAST:event_btnAgregarDispositivoActionPerformed

    private void txtIdDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdDispositivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdDispositivoActionPerformed

    private void comboHabDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHabDispositivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboHabDispositivosActionPerformed

    private void txtNomDispositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomDispositivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomDispositivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int deAcuerdo = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Estás seguro de que querés vaciar todo el registro del historial?", 
            "Limpiar Historial", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (deAcuerdo == javax.swing.JOptionPane.YES_OPTION) {
            txtAreaHistorial.setText(""); 
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal(new Vivienda()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AGDISPOSITIVOS;
    private javax.swing.JPanel AGSENSOR;
    private javax.swing.JPanel CONSUMO;
    private javax.swing.JPanel CREARHAB;
    private javax.swing.JPanel ESTADO;
    private javax.swing.JPanel HISTORIAL;
    private javax.swing.JPanel SIMULACION;
    private javax.swing.JButton btnAgregarDispositivo;
    private javax.swing.JButton btnAgregarSensor;
    private javax.swing.JButton btnCalcularConsumo;
    private javax.swing.JButton btnControlarDispositivo;
    private javax.swing.JButton btnCrearHabitacion;
    private javax.swing.JButton btnEliminarCasa;
    private javax.swing.JButton btnGuardarSalir;
    private javax.swing.JButton btnSimularEvento;
    private javax.swing.JButton btnVerEstado;
    private javax.swing.JComboBox<String> comboHabDispositivos;
    private javax.swing.JComboBox<String> comboHabEventos;
    private javax.swing.JComboBox<String> comboHabSensores;
    private javax.swing.JComboBox<String> comboOpcionesConsumo;
    private javax.swing.JComboBox<String> comboTipoDispositivo;
    private javax.swing.JComboBox<String> comboTipoEvento;
    private javax.swing.JComboBox<String> comboTipoSensor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane txtAreaConsum;
    private javax.swing.JTextArea txtAreaConsumo;
    private javax.swing.JTextArea txtAreaEstado;
    private javax.swing.JTextArea txtAreaHistorial;
    private javax.swing.JTextField txtIdDispositivo;
    private javax.swing.JTextField txtIdSensor;
    private javax.swing.JTextField txtNomDispositivo;
    private javax.swing.JTextField txtNomHabitacion;
    private javax.swing.JTextField txtNomSensor;
    // End of variables declaration//GEN-END:variables
}
